/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Button: typeof import('antd').Button
  const Checkbox: typeof import('antd').Checkbox
  const ConfigProvider: typeof import('antd').ConfigProvider
  const DeleteOutlined: typeof import('@ant-design/icons').DeleteOutlined
  const Fragment: typeof import('react').Fragment
  const GithubOutlined: typeof import('@ant-design/icons').GithubOutlined
  const HashRouter: typeof import('react-router-dom').HashRouter
  const InboxOutlined: typeof import('@ant-design/icons').InboxOutlined
  const Input: typeof import('antd').Input
  const Navigate: typeof import('react-router-dom').Navigate
  const Select: typeof import('antd').Select
  const SendOutlined: typeof import('@ant-design/icons').SendOutlined
  const Skeleton: typeof import('antd').Skeleton
  const Space: typeof import('antd').Space
  const StrictMode: typeof import('react').StrictMode
  const Suspense: typeof import('react').Suspense
  const Tag: typeof import('antd').Tag
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const theme: typeof import('antd').theme
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
