name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch where the build artifacts will be pushed
          folder: build # The folder containing the build artifacts

      - name: Configure Custom Domain
        run: |
          echo 'todo.colax.co' > ./build/CNAME
          cat ./build/CNAME

      - name: Commit and Push Custom Domain
        run: |
          cd ./build
          git config user.name "bohecola"
          git config user.email "bohecola@outlook.com"
          git add CNAME
          git commit -m "Add custom domain"
          git push origin gh-pages
